version: '3'
services:
  backend:
    build: ../back-end

  frontend:
    build: ../front-end
    volumes:
      - assets-volume:/frontend

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - assets-volume:/frontend:ro
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  assets-volume:
