version: '3'
services:
  backend:
    build: ../back-end
    depends_on:
      - postgres

  frontend:
    build: ../front-end
    volumes:
      - assets-volume:/frontend

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - assets-volume:/frontend:ro
      - ./nginx.conf:/etc/nginx/nginx.conf

  postgres:
    image: postgres:alpine
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "web_pages_db"
    volumes:
        - .:/tmp/data/

volumes:
  assets-volume:
