version: '3'
services:
  backend:
    build: 
       context: ./
       dockerfile: Dockerfile-test
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "web_pages_db"
    volumes:
        - .:/tmp/data

